name: AKS Deployment Environment Setup

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HUB_RG_LOCATION: centralus
  SPOKE_RG_LOCATION: centralus
  RESOURCE_LOCATION : eastus2
  HUB_RG_NAME: rg-enterprise-networking-hubs
  SPOKE_RG_NAME: rg-enterprise-networking-spokes


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Create AKS Prerequisites
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Login into your Azure Subscription using your Azure credentials - make sure the credentials has write permissions for the specific resource group/subscription. The credentials should be stored in GitHub Secrets - (Go to Settings Tab ->Secrets)
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create the necessary Prerequisites
    - name: Azure CLI - Create AAD and RBAC Permissions 
      id: aks-cluster
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/automationscripts/setup-prerequisites.sh
          $GITHUB_WORKSPACE/automationscripts/setup-prerequisites.sh

    # Create the base networking setup
    - name: Azure CLI - Create the Base Networking setup for the AKS deployment
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/automationscripts/deployBaseNetwork.sh
          $GITHUB_WORKSPACE/automationscripts/deployBaseNetwork.sh ${{ env.HUB_RG_LOCATION }} ${{ env.SPOKE_RG_LOCATION}} ${{ env.RESOURCE_LOCATION }} ${{env.HUB_RG_NAME}} ${{env.SPOKE_RG_NAME}}

