# This is a basic workflow to help you get started with Actions

name: TestWorkflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  EXECUTE_STEP: 'true'
  TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId}}
  SP_OBJECT_ID: ${{ secrets.SPOBJECTID}} #'a2855bef-2150-4983-8b1b-6d6d2bcc52f0'
  HUB_RG_LOCATION: 'centralus'
  SPOKE_RG_LOCATION: 'centralus'
  RESOURCE_LOCATION : 'eastus2'
  HUB_RG_NAME: 'rg-enterprise-networking-hubs'
  SPOKE_RG_NAME: 'rg-enterprise-networking-spokes'
  DEPLOY_TLS_CERTS: 'true'
  DEPLOY_BASE_NETWORK: 'false'
  DEPLOY_AKS_CLUSTER: 'false'
  RESOURCE_GROUP_LOCATION: 'eastus2'  # The location where the resource group is going to be created
  RESOURCE_GROUP: 'rg-bu0001a0008'    # The name for the AKS cluster resource group


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ env.EXECUTE_STEP == 'true'}}
        run: |
          Tenant_Id = ${{env.TENANT_ID}}
          SP_Id = ${{env.SP_OBJECT_ID}}
          echo "Tenant Id length: ${#Tenant_Id} "
          echo "SP Object ID length: ${#SP_Id}"

      # Execute the post-deployment ops
      - name: Azure CLI - keyvault/PodIdentity/ACR-Image-Import/Ingress&Workload Deployment
        uses: Azure/cli@v1.0.0
        with:
         inlineScript: |
          chmod +x $GITHUB_WORKSPACE/automationscripts/testDeployment.sh
          $GITHUB_WORKSPACE/automationscripts/testDeployment.sh ${{ env.RESOURCE_GROUP }} ${{env.SPOKE_RG_NAME}} ${{env.TENANT_ID}} ${{env.SP_OBJECT_ID}}
