# This is a basic workflow to help you get started with Actions

name: TestWorkflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  EXECUTE_STEP: 'false'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ env.EXECUTE_STEP == 'true'}}
        run: |
          echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' | jq '.'

      - name: Azure CLI - Deploy AKS cluster
        id: aks-cluster-cli
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az aks install-cli
             echo $(kubectl version --client)
